/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IbbtcVaultZap } from './IbbtcVaultZap';
export type { VoteLockedDeposit } from './VoteLockedDeposit';
export * as factories from './factories';
export { IbbtcVaultZap__factory } from './factories/IbbtcVaultZap__factory';
export { VoteLockedDeposit__factory } from './factories/VoteLockedDeposit__factory';
