/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
	ethers,
	EventFilter,
	Signer,
	BigNumber,
	BigNumberish,
	PopulatedTransaction,
	BaseContract,
	ContractTransaction,
	Overrides,
	CallOverrides,
} from 'ethers';
import { BytesLike } from '@ethersproject/bytes';
import { Listener, Provider } from '@ethersproject/providers';
import { FunctionFragment, EventFragment, Result } from '@ethersproject/abi';
import type { TypedEventFilter, TypedEvent, TypedListener } from './common';

interface YearnBtcPeakInterface extends ethers.utils.Interface {
	functions: {
		'approveContractAccess(address)': FunctionFragment;
		'approved(address)': FunctionFragment;
		'blockLock(address)': FunctionFragment;
		'byvWBTC()': FunctionFragment;
		'calcMint(uint256)': FunctionFragment;
		'calcRedeem(uint256)': FunctionFragment;
		'core()': FunctionFragment;
		'mint(uint256,bytes32[])': FunctionFragment;
		'owner()': FunctionFragment;
		'portfolioValue()': FunctionFragment;
		'redeem(uint256)': FunctionFragment;
		'revokeContractAccess(address)': FunctionFragment;
		'transferOwnership(address)': FunctionFragment;
	};

	encodeFunctionData(functionFragment: 'approveContractAccess', values: [string]): string;
	encodeFunctionData(functionFragment: 'approved', values: [string]): string;
	encodeFunctionData(functionFragment: 'blockLock', values: [string]): string;
	encodeFunctionData(functionFragment: 'byvWBTC', values?: undefined): string;
	encodeFunctionData(functionFragment: 'calcMint', values: [BigNumberish]): string;
	encodeFunctionData(functionFragment: 'calcRedeem', values: [BigNumberish]): string;
	encodeFunctionData(functionFragment: 'core', values?: undefined): string;
	encodeFunctionData(functionFragment: 'mint', values: [BigNumberish, BytesLike[]]): string;
	encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
	encodeFunctionData(functionFragment: 'portfolioValue', values?: undefined): string;
	encodeFunctionData(functionFragment: 'redeem', values: [BigNumberish]): string;
	encodeFunctionData(functionFragment: 'revokeContractAccess', values: [string]): string;
	encodeFunctionData(functionFragment: 'transferOwnership', values: [string]): string;

	decodeFunctionResult(functionFragment: 'approveContractAccess', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'approved', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'blockLock', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'byvWBTC', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'calcMint', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'calcRedeem', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'core', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'mint', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'portfolioValue', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'redeem', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'revokeContractAccess', data: BytesLike): Result;
	decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;

	events: {
		'Mint(address,uint256,uint256)': EventFragment;
		'OwnershipTransferred(address,address)': EventFragment;
		'Redeem(address,uint256,uint256)': EventFragment;
	};

	getEvent(nameOrSignatureOrTopic: 'Mint'): EventFragment;
	getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment;
	getEvent(nameOrSignatureOrTopic: 'Redeem'): EventFragment;
}

export type MintEvent = TypedEvent<
	[string, BigNumber, BigNumber] & {
		account: string;
		ibBTC: BigNumber;
		byvWBTC: BigNumber;
	}
>;

export type OwnershipTransferredEvent = TypedEvent<[string, string] & { previousOwner: string; newOwner: string }>;

export type RedeemEvent = TypedEvent<
	[string, BigNumber, BigNumber] & {
		account: string;
		ibBTC: BigNumber;
		byvWBTC: BigNumber;
	}
>;

export class YearnBtcPeak extends BaseContract {
	connect(signerOrProvider: Signer | Provider | string): this;
	attach(addressOrName: string): this;
	deployed(): Promise<this>;

	listeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>,
	): Array<TypedListener<EventArgsArray, EventArgsObject>>;
	off<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>,
	): this;
	on<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>,
	): this;
	once<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>,
	): this;
	removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>,
	): this;
	removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
	): this;

	listeners(eventName?: string): Array<Listener>;
	off(eventName: string, listener: Listener): this;
	on(eventName: string, listener: Listener): this;
	once(eventName: string, listener: Listener): this;
	removeListener(eventName: string, listener: Listener): this;
	removeAllListeners(eventName?: string): this;

	queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
		event: TypedEventFilter<EventArgsArray, EventArgsObject>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined,
	): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

	interface: YearnBtcPeakInterface;

	functions: {
		approveContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<ContractTransaction>;

		approved(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

		blockLock(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

		byvWBTC(overrides?: CallOverrides): Promise<[string]>;

		calcMint(
			inAmount: BigNumberish,
			overrides?: CallOverrides,
		): Promise<[BigNumber, BigNumber] & { bBTC: BigNumber; fee: BigNumber }>;

		calcRedeem(
			bBtc: BigNumberish,
			overrides?: CallOverrides,
		): Promise<
			[BigNumber, BigNumber, BigNumber] & {
				sett: BigNumber;
				fee: BigNumber;
				max: BigNumber;
			}
		>;

		core(overrides?: CallOverrides): Promise<[string]>;

		mint(
			inAmount: BigNumberish,
			merkleProof: BytesLike[],
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<ContractTransaction>;

		owner(overrides?: CallOverrides): Promise<[string] & { _owner: string }>;

		portfolioValue(overrides?: CallOverrides): Promise<[BigNumber]>;

		redeem(
			inAmount: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<ContractTransaction>;

		revokeContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<ContractTransaction>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<ContractTransaction>;
	};

	approveContractAccess(
		account: string,
		overrides?: Overrides & { from?: string | Promise<string> },
	): Promise<ContractTransaction>;

	approved(arg0: string, overrides?: CallOverrides): Promise<boolean>;

	blockLock(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

	byvWBTC(overrides?: CallOverrides): Promise<string>;

	calcMint(
		inAmount: BigNumberish,
		overrides?: CallOverrides,
	): Promise<[BigNumber, BigNumber] & { bBTC: BigNumber; fee: BigNumber }>;

	calcRedeem(
		bBtc: BigNumberish,
		overrides?: CallOverrides,
	): Promise<
		[BigNumber, BigNumber, BigNumber] & {
			sett: BigNumber;
			fee: BigNumber;
			max: BigNumber;
		}
	>;

	core(overrides?: CallOverrides): Promise<string>;

	mint(
		inAmount: BigNumberish,
		merkleProof: BytesLike[],
		overrides?: Overrides & { from?: string | Promise<string> },
	): Promise<ContractTransaction>;

	owner(overrides?: CallOverrides): Promise<string>;

	portfolioValue(overrides?: CallOverrides): Promise<BigNumber>;

	redeem(
		inAmount: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> },
	): Promise<ContractTransaction>;

	revokeContractAccess(
		account: string,
		overrides?: Overrides & { from?: string | Promise<string> },
	): Promise<ContractTransaction>;

	transferOwnership(
		newOwner: string,
		overrides?: Overrides & { from?: string | Promise<string> },
	): Promise<ContractTransaction>;

	callStatic: {
		approveContractAccess(account: string, overrides?: CallOverrides): Promise<void>;

		approved(arg0: string, overrides?: CallOverrides): Promise<boolean>;

		blockLock(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

		byvWBTC(overrides?: CallOverrides): Promise<string>;

		calcMint(
			inAmount: BigNumberish,
			overrides?: CallOverrides,
		): Promise<[BigNumber, BigNumber] & { bBTC: BigNumber; fee: BigNumber }>;

		calcRedeem(
			bBtc: BigNumberish,
			overrides?: CallOverrides,
		): Promise<
			[BigNumber, BigNumber, BigNumber] & {
				sett: BigNumber;
				fee: BigNumber;
				max: BigNumber;
			}
		>;

		core(overrides?: CallOverrides): Promise<string>;

		mint(inAmount: BigNumberish, merkleProof: BytesLike[], overrides?: CallOverrides): Promise<BigNumber>;

		owner(overrides?: CallOverrides): Promise<string>;

		portfolioValue(overrides?: CallOverrides): Promise<BigNumber>;

		redeem(inAmount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

		revokeContractAccess(account: string, overrides?: CallOverrides): Promise<void>;

		transferOwnership(newOwner: string, overrides?: CallOverrides): Promise<void>;
	};

	filters: {
		'Mint(address,uint256,uint256)'(
			account?: null,
			ibBTC?: null,
			byvWBTC?: null,
		): TypedEventFilter<[string, BigNumber, BigNumber], { account: string; ibBTC: BigNumber; byvWBTC: BigNumber }>;

		Mint(
			account?: null,
			ibBTC?: null,
			byvWBTC?: null,
		): TypedEventFilter<[string, BigNumber, BigNumber], { account: string; ibBTC: BigNumber; byvWBTC: BigNumber }>;

		'OwnershipTransferred(address,address)'(
			previousOwner?: string | null,
			newOwner?: string | null,
		): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>;

		OwnershipTransferred(
			previousOwner?: string | null,
			newOwner?: string | null,
		): TypedEventFilter<[string, string], { previousOwner: string; newOwner: string }>;

		'Redeem(address,uint256,uint256)'(
			account?: null,
			ibBTC?: null,
			byvWBTC?: null,
		): TypedEventFilter<[string, BigNumber, BigNumber], { account: string; ibBTC: BigNumber; byvWBTC: BigNumber }>;

		Redeem(
			account?: null,
			ibBTC?: null,
			byvWBTC?: null,
		): TypedEventFilter<[string, BigNumber, BigNumber], { account: string; ibBTC: BigNumber; byvWBTC: BigNumber }>;
	};

	estimateGas: {
		approveContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<BigNumber>;

		approved(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

		blockLock(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

		byvWBTC(overrides?: CallOverrides): Promise<BigNumber>;

		calcMint(inAmount: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

		calcRedeem(bBtc: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

		core(overrides?: CallOverrides): Promise<BigNumber>;

		mint(
			inAmount: BigNumberish,
			merkleProof: BytesLike[],
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<BigNumber>;

		owner(overrides?: CallOverrides): Promise<BigNumber>;

		portfolioValue(overrides?: CallOverrides): Promise<BigNumber>;

		redeem(inAmount: BigNumberish, overrides?: Overrides & { from?: string | Promise<string> }): Promise<BigNumber>;

		revokeContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<BigNumber>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<BigNumber>;
	};

	populateTransaction: {
		approveContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<PopulatedTransaction>;

		approved(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

		blockLock(arg0: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;

		byvWBTC(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		calcMint(inAmount: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

		calcRedeem(bBtc: BigNumberish, overrides?: CallOverrides): Promise<PopulatedTransaction>;

		core(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		mint(
			inAmount: BigNumberish,
			merkleProof: BytesLike[],
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<PopulatedTransaction>;

		owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		portfolioValue(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		redeem(
			inAmount: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<PopulatedTransaction>;

		revokeContractAccess(
			account: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<PopulatedTransaction>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> },
		): Promise<PopulatedTransaction>;
	};
}
