#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

yarn eslint "**/*.{js,jsx,json,ts,tsx}" --fix --no-error-on-unmatched-pattern --ignore-pattern build/ --ignore-pattern node_modules/ --max-warnings=0
