name: Test Coverage

on:
  pull_request:
    branches: [ development ]
  push:
    branches: [ test-coverage ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 80
          package-manager: yarn
          test-script: yarn test --silent --ci --coverage --coverageReporters="text" --coverageReporters="text-summary"
