name: Build Storybook Preview
on:
    pull_request:
        branches:
            - development
        paths:
            - src/stories/**
            - .storybook/**
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build Storybook
              run: yarn build-storybook
            - name: Deploy to Netlify
              uses: nwtgck/actions-netlify@v1.2.3
              with:
                  publish-dir: './storybook-static'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  deploy-message: 'Deploy preview'
              env:
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_STORYBOOK_AUTH_TOKEN }}
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STORYBOOK_SITE_ID }}
              timeout-minutes: 1
